admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 7777
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          tracing:
            verbose: false
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: banana
          http_filters:
          - name: envoy.filters.http.jwendell
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.jwendell.v3.Decoder
              header_key: xuxa
              header_value: xuxo
          - name: envoy.filters.http.router
  clusters:
  - name: banana
    connect_timeout: 1s
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: banana
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: "3.211.1.78"
                    port_value: 80
            - endpoint:
                address:
                  socket_address:
                    address: "52.6.34.179"
                    port_value: 80
